import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cursor } from "@/components/cursor";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full cursor-none flex-col bg-background font-sans text-foreground">
        <div className="fixed -inset-1/2 z-[-1] animate-[bg-animation_0.2s_infinite] bg-[url('/images/noise-transparent.png')] bg-repeat opacity-90" />
        <Cursor />
        {children}
      </body>
    </html>
  );
}
